# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

# triggering branch
trigger:
- main
- master
- develop

parameters:
  - name: DATADOG_CLIENT_TOKEN
    type: string
    default: ''
  - name: DATADOG_APP_ID
    type: string
    default: ''
  - name: IAM_CLIENT_ID
    type: string
    default: ''
  - name: KOSMOS_LICENSE_KEY
    type: string
    default: ''
  - name: KOSMOS_DVC_ID
    type: string
    default: ''
  - name: ONE_SPAN_TEAM_ID
    type: string
    default: ''
  - name: ONE_SPAN_ACCOUNT_IDENTIFIER
    type: string
    default: ''

variables:
  - group: 'hhc-cahcm' # this loads the secure variable group that contains the cert password
  - name: projectName
    value: Companion
  - name: buildNumber
    value: $[format('{0:yyyyMMddHHmmss}', pipeline.startTime)]
  - name: isMaster
    value: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/master')]

pool:
  vmImage: 'macos-latest'


steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, 11, 12, default, specifyPath