# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

# triggering branch
trigger:
- main
- master
- develop

variables:
  - name: projectName
    value: Companion
  - name: buildNumber
    value: $[format('{0:yyyyMMddHHmmss}', pipeline.startTime)]
  - name: isMaster
    value: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/master')]

pool:
  vmImage: 'macos-latest'

steps:
# run command line show current time
- script: echo $(date)
  displayName: 'Show current time'
# script to print AzurePipeline varaible named "TEST"
- script: echo $(TEST)
  displayName: 'Print AzurePipeline variable'
- task: Xcode@5
  displayName: 'Build iOS'
  inputs:
    actions: 'build'
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, 11, 12, default, specifyPath